# Generated by Django 3.0.5 on 2022-12-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.FloatField(default=65),
            preserve_default=False,
        ),
    ]
