# Generated by Django 3.0.5 on 2022-12-17 17:18

from django.db import migrations, models
import ecomerce.shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_photo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='mediafiles', validators=[ecomerce.shop.validators.validate_file_size]),
        ),
    ]
